// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/interprete/Lexer.jflex

// ------------  Paquete e importaciones ------------
package interprete; 

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\1\22\0\1\1\1\4"+
    "\1\5\2\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\12\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\40\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\3\40\1\55\1\56\1\57\1\60"+
    "\1\61\1\0\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\62"+
    "\1\45\1\46\1\40\1\63\1\50\1\64\1\52\1\53"+
    "\1\54\3\40\1\65\1\66\1\67\7\0\1\3\252\0"+
    "\2\70\115\0\1\71\u01a8\0\2\3\u0100\0\1\72\325\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\21\23\1\24\1\25"+
    "\1\26\1\1\1\27\1\1\1\30\2\1\1\31\1\0"+
    "\1\32\1\0\1\33\2\0\1\34\1\0\1\35\1\0"+
    "\1\36\1\37\1\40\6\23\1\41\4\23\1\0\1\42"+
    "\3\23\1\0\13\23\1\0\1\43\1\42\2\0\1\44"+
    "\1\0\1\45\10\23\1\0\2\23\1\46\1\0\1\47"+
    "\2\23\1\0\1\23\1\50\1\23\1\0\6\23\1\0"+
    "\1\23\1\51\1\23\1\0\1\23\1\0\1\47\2\0"+
    "\2\35\1\23\1\52\1\23\1\53\2\23\1\0\2\23"+
    "\2\54\1\0\2\55\1\23\2\56\2\23\1\0\6\23"+
    "\1\0\1\23\1\0\1\57\2\60\1\23\3\0\1\23"+
    "\2\61\1\62\1\23\1\0\1\62\2\23\1\57\1\23"+
    "\1\63\1\23\1\0\2\23\1\64\3\23\1\0\1\23"+
    "\1\0\2\65\2\0\1\66\1\23\1\0\1\23\1\67"+
    "\1\70\1\23\1\0\1\71\1\72\1\23\1\73\1\74"+
    "\1\73\1\23\2\0\1\74\1\23\1\0\1\75\2\76"+
    "\2\23\2\0\2\77\1\23\1\0\2\100\1\23\1\0"+
    "\2\101";

  private static int [] zzUnpackAction() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\73\0\166\0\261\0\73\0\354\0\u0127"+
    "\0\73\0\73\0\u0162\0\73\0\73\0\u019d\0\73\0\u01d8"+
    "\0\u0213\0\73\0\73\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a"+
    "\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7\0\u0512"+
    "\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\u0674\0\u06af\0\73"+
    "\0\73\0\73\0\u06ea\0\73\0\u0725\0\73\0\u0760\0\u079b"+
    "\0\73\0\261\0\73\0\u07d6\0\73\0\u0811\0\u084c\0\73"+
    "\0\u0887\0\u08c2\0\u08fd\0\73\0\73\0\73\0\u0938\0\u0973"+
    "\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b"+
    "\0\u0b86\0\u0bc1\0\u0461\0\u0bfc\0\u0c37\0\u0c72\0\u0cad\0\u0ce8"+
    "\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0"+
    "\0\u0efb\0\u0f36\0\u06ea\0\73\0\73\0\u0f71\0\u0fac\0\73"+
    "\0\u0fe7\0\u08fd\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149"+
    "\0\u1184\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u0461\0\u12ab\0\u0461"+
    "\0\u12e6\0\u1321\0\u135c\0\u1397\0\u0461\0\u13d2\0\u140d\0\u1448"+
    "\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5\0\u0461"+
    "\0\u1620\0\u165b\0\u1696\0\u16d1\0\73\0\u170c\0\u1747\0\u0fe7"+
    "\0\u0887\0\u1782\0\u0461\0\u17bd\0\u0461\0\u17f8\0\u1833\0\u186e"+
    "\0\u18a9\0\u18e4\0\u0461\0\73\0\u191f\0\u0461\0\73\0\u195a"+
    "\0\u0461\0\73\0\u1995\0\u19d0\0\u1a0b\0\u1a46\0\u1a81\0\u1abc"+
    "\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e\0\u0461\0\u0461"+
    "\0\73\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a\0\u1d45\0\u0461\0\73"+
    "\0\u0461\0\u1d80\0\u1dbb\0\73\0\u1df6\0\u1e31\0\73\0\u1e6c"+
    "\0\u0461\0\u1ea7\0\u1ee2\0\u1f1d\0\u1f58\0\u0461\0\u1f93\0\u1fce"+
    "\0\u2009\0\u2044\0\u207f\0\u20ba\0\u0461\0\73\0\u20f5\0\u2130"+
    "\0\u0461\0\u216b\0\u21a6\0\u21e1\0\u0461\0\u0461\0\u221c\0\u2257"+
    "\0\u0461\0\u0461\0\u2292\0\u0461\0\u0461\0\73\0\u22cd\0\u2308"+
    "\0\u2343\0\73\0\u237e\0\u23b9\0\u0461\0\u0461\0\73\0\u23f4"+
    "\0\u242f\0\u246a\0\u24a5\0\u0461\0\73\0\u24e0\0\u251b\0\u0461"+
    "\0\73\0\u2556\0\u2591\0\u0461\0\73";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\2\35\1\36\2\35\1\37"+
    "\1\40\1\41\1\35\1\42\1\43\1\44\1\45\1\35"+
    "\1\46\1\47\1\50\1\2\1\51\1\52\1\53\1\41"+
    "\1\43\1\45\1\54\1\55\1\56\1\57\1\60\1\2"+
    "\120\0\1\61\45\0\5\62\1\63\50\62\1\64\14\62"+
    "\7\0\1\65\63\0\10\66\1\0\45\66\1\67\14\66"+
    "\13\0\1\70\100\0\1\21\64\0\1\71\4\0\1\72"+
    "\71\0\1\73\1\0\1\21\76\0\1\74\72\0\1\75"+
    "\72\0\1\76\66\0\1\35\5\0\17\35\1\77\6\35"+
    "\4\0\4\35\27\0\1\35\5\0\16\35\1\100\1\35"+
    "\1\101\5\35\4\0\2\35\1\101\1\35\27\0\1\35"+
    "\5\0\7\35\1\102\6\35\1\103\7\35\4\0\4\35"+
    "\27\0\1\35\5\0\4\35\1\104\11\35\1\105\7\35"+
    "\4\0\4\35\27\0\1\35\5\0\13\35\1\106\12\35"+
    "\4\0\4\35\27\0\1\35\5\0\1\107\7\35\1\110"+
    "\5\35\1\111\7\35\4\0\4\35\3\0\1\112\23\0"+
    "\1\35\5\0\26\35\4\0\4\35\27\0\1\35\5\0"+
    "\5\35\1\113\7\35\1\114\10\35\4\0\1\35\1\114"+
    "\2\35\27\0\1\35\5\0\4\35\1\115\3\35\1\116"+
    "\15\35\4\0\4\35\3\0\1\117\23\0\1\35\5\0"+
    "\1\120\25\35\4\0\4\35\27\0\1\35\5\0\4\35"+
    "\1\121\21\35\4\0\4\35\27\0\1\35\5\0\20\35"+
    "\1\122\5\35\4\0\2\35\1\122\1\35\27\0\1\35"+
    "\5\0\4\35\1\123\11\35\1\124\7\35\4\0\4\35"+
    "\27\0\1\35\5\0\22\35\1\125\3\35\4\0\3\35"+
    "\1\125\27\0\1\35\5\0\16\35\1\126\1\35\1\127"+
    "\5\35\4\0\2\35\1\127\1\35\27\0\1\35\5\0"+
    "\1\130\15\35\1\131\7\35\4\0\4\35\27\0\1\35"+
    "\5\0\7\35\1\132\16\35\4\0\4\35\35\0\26\35"+
    "\4\0\1\133\3\35\74\0\1\134\40\0\1\135\7\0"+
    "\1\136\15\0\1\136\61\0\1\137\12\0\1\137\13\0"+
    "\1\62\2\0\1\62\45\0\1\62\3\0\3\62\16\0"+
    "\1\140\67\0\1\66\2\0\1\66\45\0\1\66\3\0"+
    "\3\66\6\0\13\71\1\141\57\71\2\72\1\0\70\72"+
    "\21\0\1\142\72\0\1\35\5\0\17\35\1\143\6\35"+
    "\4\0\4\35\27\0\1\35\5\0\16\35\1\144\7\35"+
    "\4\0\4\35\27\0\1\35\5\0\4\35\1\145\21\35"+
    "\4\0\4\35\27\0\1\35\5\0\1\146\25\35\4\0"+
    "\4\35\27\0\1\35\5\0\15\35\1\147\10\35\4\0"+
    "\1\35\1\147\2\35\27\0\1\35\5\0\5\35\1\150"+
    "\20\35\4\0\4\35\27\0\1\35\5\0\23\35\1\151"+
    "\2\35\4\0\4\35\27\0\1\35\5\0\21\35\1\152"+
    "\4\35\4\0\4\35\4\0\1\153\22\0\1\35\5\0"+
    "\13\35\1\154\12\35\4\0\4\35\27\0\1\35\5\0"+
    "\15\35\1\155\10\35\4\0\1\35\1\155\2\35\27\0"+
    "\1\35\5\0\20\35\1\156\5\35\4\0\2\35\1\156"+
    "\1\35\52\0\1\157\15\0\1\157\31\0\1\35\5\0"+
    "\22\35\1\160\3\35\4\0\3\35\1\160\27\0\1\35"+
    "\5\0\15\35\1\161\10\35\4\0\1\35\1\161\2\35"+
    "\27\0\1\35\5\0\21\35\1\162\4\35\4\0\4\35"+
    "\4\0\1\163\51\0\1\163\20\0\1\163\22\0\1\35"+
    "\5\0\22\35\1\164\3\35\4\0\3\35\1\164\27\0"+
    "\1\35\5\0\25\35\1\165\4\0\4\35\27\0\1\35"+
    "\5\0\10\35\1\166\15\35\4\0\4\35\3\0\1\167"+
    "\23\0\1\35\5\0\14\35\1\170\5\35\1\171\3\35"+
    "\4\0\3\35\1\171\27\0\1\35\5\0\23\35\1\172"+
    "\2\35\4\0\4\35\27\0\1\35\5\0\1\173\17\35"+
    "\1\174\5\35\4\0\2\35\1\174\1\35\27\0\1\35"+
    "\5\0\21\35\1\175\4\35\4\0\4\35\4\0\1\176"+
    "\22\0\1\35\5\0\23\35\1\177\2\35\4\0\4\35"+
    "\27\0\1\35\5\0\20\35\1\200\5\35\4\0\2\35"+
    "\1\200\1\35\27\0\1\35\5\0\10\35\1\201\15\35"+
    "\4\0\4\35\3\0\1\202\23\0\1\35\5\0\10\35"+
    "\1\203\15\35\4\0\4\35\3\0\1\204\53\0\1\205"+
    "\12\0\1\205\35\0\1\206\17\0\1\207\13\0\1\207"+
    "\7\0\13\71\1\210\4\71\1\211\52\71\21\0\1\35"+
    "\5\0\4\35\1\212\21\35\4\0\4\35\27\0\1\35"+
    "\5\0\13\35\1\213\12\35\4\0\4\35\27\0\1\35"+
    "\5\0\1\214\25\35\4\0\4\35\27\0\1\35\5\0"+
    "\20\35\1\215\5\35\4\0\2\35\1\215\1\35\27\0"+
    "\1\35\5\0\21\35\1\216\1\217\3\35\4\0\3\35"+
    "\1\217\4\0\1\220\22\0\1\35\5\0\1\221\25\35"+
    "\4\0\4\35\27\0\1\35\5\0\1\35\1\222\24\35"+
    "\4\0\4\35\27\0\1\35\5\0\4\35\1\223\21\35"+
    "\4\0\4\35\41\0\1\224\60\0\1\35\5\0\21\35"+
    "\1\177\4\35\4\0\4\35\4\0\1\225\22\0\1\35"+
    "\5\0\3\35\1\226\22\35\4\0\4\35\40\0\1\227"+
    "\61\0\1\35\5\0\6\35\1\230\17\35\4\0\4\35"+
    "\27\0\1\35\5\0\22\35\1\231\3\35\4\0\3\35"+
    "\1\231\57\0\1\232\12\0\1\232\27\0\1\35\5\0"+
    "\2\35\1\233\23\35\4\0\4\35\27\0\1\35\5\0"+
    "\15\35\1\234\10\35\4\0\1\35\1\234\2\35\52\0"+
    "\1\235\15\0\1\235\31\0\1\35\5\0\16\35\1\236"+
    "\7\35\4\0\4\35\27\0\1\35\5\0\23\35\1\237"+
    "\2\35\4\0\4\35\27\0\1\35\5\0\15\35\1\240"+
    "\10\35\4\0\1\35\1\240\2\35\27\0\1\35\5\0"+
    "\20\35\1\241\5\35\4\0\2\35\1\241\1\35\27\0"+
    "\1\35\5\0\10\35\1\242\12\35\1\243\2\35\4\0"+
    "\4\35\3\0\1\244\23\0\1\35\5\0\22\35\1\245"+
    "\3\35\4\0\3\35\1\245\57\0\1\246\12\0\1\246"+
    "\27\0\1\35\5\0\4\35\1\247\21\35\4\0\4\35"+
    "\27\0\1\35\5\0\3\35\1\250\22\35\4\0\4\35"+
    "\40\0\1\251\61\0\1\35\5\0\13\35\1\252\12\35"+
    "\4\0\4\35\50\0\1\253\77\0\1\254\13\0\1\254"+
    "\46\0\1\244\12\0\1\255\15\0\1\244\23\0\1\35"+
    "\5\0\15\35\1\256\10\35\4\0\1\35\1\256\2\35"+
    "\27\0\1\35\5\0\12\35\1\257\13\35\4\0\4\35"+
    "\5\0\1\260\21\0\1\35\5\0\22\35\1\261\3\35"+
    "\4\0\3\35\1\261\27\0\1\35\5\0\10\35\1\262"+
    "\15\35\4\0\4\35\3\0\1\263\53\0\1\264\12\0"+
    "\1\264\27\0\1\35\5\0\23\35\1\265\2\35\4\0"+
    "\4\35\27\0\1\35\5\0\13\35\1\266\12\35\4\0"+
    "\4\35\41\0\1\267\60\0\1\35\5\0\22\35\1\270"+
    "\3\35\4\0\3\35\1\270\27\0\1\35\5\0\7\35"+
    "\1\271\16\35\4\0\4\35\27\0\1\35\5\0\22\35"+
    "\1\272\3\35\4\0\3\35\1\272\57\0\1\273\12\0"+
    "\1\273\27\0\1\35\5\0\24\35\1\274\1\35\4\0"+
    "\4\35\27\0\1\35\5\0\20\35\1\275\5\35\4\0"+
    "\2\35\1\275\1\35\27\0\1\35\5\0\3\35\1\276"+
    "\22\35\4\0\4\35\27\0\1\35\5\0\22\35\1\277"+
    "\3\35\4\0\3\35\1\277\27\0\1\35\5\0\15\35"+
    "\1\300\10\35\4\0\1\35\1\300\2\35\27\0\1\35"+
    "\5\0\2\35\1\301\23\35\4\0\4\35\52\0\1\302"+
    "\15\0\1\302\31\0\1\35\5\0\20\35\1\303\5\35"+
    "\4\0\2\35\1\303\1\35\55\0\1\304\13\0\1\304"+
    "\30\0\1\35\5\0\4\35\1\305\21\35\4\0\4\35"+
    "\41\0\1\306\110\0\1\307\12\0\1\307\37\0\1\310"+
    "\62\0\1\35\5\0\3\35\1\311\22\35\4\0\4\35"+
    "\27\0\1\35\5\0\15\35\1\312\10\35\4\0\1\35"+
    "\1\312\2\35\52\0\1\313\15\0\1\313\31\0\1\35"+
    "\5\0\13\35\1\314\12\35\4\0\4\35\27\0\1\35"+
    "\5\0\4\35\1\315\21\35\4\0\4\35\27\0\1\35"+
    "\5\0\7\35\1\316\16\35\4\0\4\35\27\0\1\35"+
    "\5\0\13\35\1\317\12\35\4\0\4\35\50\0\1\320"+
    "\51\0\1\35\5\0\4\35\1\321\21\35\4\0\4\35"+
    "\27\0\1\35\5\0\15\35\1\322\10\35\4\0\1\35"+
    "\1\322\2\35\27\0\1\35\5\0\26\35\4\0\1\323"+
    "\3\35\27\0\1\35\5\0\6\35\1\324\17\35\4\0"+
    "\4\35\27\0\1\35\5\0\22\35\1\325\3\35\4\0"+
    "\3\35\1\325\43\0\1\326\56\0\1\35\5\0\10\35"+
    "\1\327\15\35\4\0\4\35\3\0\1\330\41\0\1\330"+
    "\30\0\1\330\63\0\1\331\62\0\1\332\12\0\1\332"+
    "\27\0\1\35\5\0\23\35\1\333\2\35\4\0\4\35"+
    "\60\0\1\334\41\0\1\35\5\0\22\35\1\335\3\35"+
    "\4\0\3\35\1\335\27\0\1\35\5\0\15\35\1\336"+
    "\10\35\4\0\1\35\1\336\2\35\52\0\1\337\15\0"+
    "\1\337\31\0\1\35\5\0\25\35\1\340\4\0\4\35"+
    "\27\0\1\35\5\0\15\35\1\341\10\35\4\0\1\35"+
    "\1\341\2\35\52\0\1\342\15\0\1\342\64\0\1\343"+
    "\37\0\1\35\5\0\4\35\1\344\21\35\4\0\4\35"+
    "\41\0\1\345\60\0\1\35\5\0\10\35\1\346\15\35"+
    "\4\0\4\35\3\0\1\347\23\0\1\35\5\0\6\35"+
    "\1\350\17\35\4\0\4\35\43\0\1\351\74\0\1\347"+
    "\30\0\1\347\23\0\1\35\5\0\22\35\1\352\3\35"+
    "\4\0\3\35\1\352\57\0\1\353\12\0\1\353\27\0"+
    "\1\35\5\0\7\35\1\354\16\35\4\0\4\35\44\0"+
    "\1\355\34\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9676];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\2\1\2\11\1\1\2\11"+
    "\1\1\1\11\2\1\2\11\24\1\3\11\1\1\1\11"+
    "\1\1\1\11\2\1\1\11\1\0\1\11\1\0\1\11"+
    "\2\0\1\11\1\0\1\1\1\0\3\11\13\1\1\0"+
    "\4\1\1\0\13\1\1\0\2\11\2\0\1\11\1\0"+
    "\11\1\1\0\3\1\1\0\3\1\1\0\3\1\1\0"+
    "\6\1\1\0\3\1\1\0\1\1\1\0\1\11\2\0"+
    "\10\1\1\0\3\1\1\11\1\0\1\1\1\11\2\1"+
    "\1\11\2\1\1\0\6\1\1\0\1\1\1\0\2\1"+
    "\1\11\1\1\3\0\2\1\1\11\2\1\1\0\1\11"+
    "\2\1\1\11\3\1\1\0\6\1\1\0\1\1\1\0"+
    "\1\1\1\11\2\0\2\1\1\0\4\1\1\0\5\1"+
    "\1\11\1\1\2\0\1\11\1\1\1\0\2\1\1\11"+
    "\2\1\2\0\1\1\1\11\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error Lexico: " + yytext() + " | Fila:" + yyline + " | Columna: " + yycolumn);
            }
          // fall through
          case 66: break;
          case 2:
            { /* Espacios en blanco se ignoran */
            }
          // fall through
          case 67: break;
          case 3:
            { return new Symbol(sym.NOT, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 4:
            { return new Symbol(sym.MODULO, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 5:
            { return new Symbol(sym.A_PARENTESIS, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 6:
            { return new Symbol(sym.C_PARENTESIS, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 7:
            { return new Symbol(sym.POR, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 8:
            { return new Symbol(sym.MAS, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 9:
            { return new Symbol(sym.COMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 10:
            { return new Symbol(sym.MENOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 11:
            { return new Symbol(sym.PUNTO, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 12:
            { return new Symbol(sym.DIVIDIR, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 13:
            { return new Symbol(sym.ENTERO, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          case 14:
            { return new Symbol(sym.DOS_P, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 15:
            { return new Symbol(sym.PYC, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 16:
            { return new Symbol(sym.MENOR_Q, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 17:
            { return new Symbol(sym.IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          case 18:
            { return new Symbol(sym.MAYOR_Q, yycolumn, yyline, yytext());
            }
          // fall through
          case 83: break;
          case 19:
            { return new Symbol(sym.ID, yycolumn, yyline, yytext());
            }
          // fall through
          case 84: break;
          case 20:
            { return new Symbol(sym.A_CORCHETE, yycolumn, yyline, yytext());
            }
          // fall through
          case 85: break;
          case 21:
            { return new Symbol(sym.C_CORCHETE, yycolumn, yyline, yytext());
            }
          // fall through
          case 86: break;
          case 22:
            { return new Symbol(sym.XOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 87: break;
          case 23:
            { return new Symbol(sym.A_LLAVE, yycolumn, yyline, yytext());
            }
          // fall through
          case 88: break;
          case 24:
            { return new Symbol(sym.C_LLAVE, yycolumn, yyline, yytext());
            }
          // fall through
          case 89: break;
          case 25:
            { return new Symbol(sym.DIFERENCIACION, yycolumn, yyline, yytext());
            }
          // fall through
          case 90: break;
          case 26:
            { return new Symbol(sym.CADENA, yycolumn, yyline, yytext().replace("\"", ""));
            }
          // fall through
          case 91: break;
          case 27:
            { return new Symbol(sym.AND, yycolumn, yyline, yytext());
            }
          // fall through
          case 92: break;
          case 28:
            { return new Symbol(sym.POTENCIA, yycolumn, yyline, yytext());
            }
          // fall through
          case 93: break;
          case 29:
            { 
            }
          // fall through
          case 94: break;
          case 30:
            { return new Symbol(sym.MENOR_IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 95: break;
          case 31:
            { return new Symbol(sym.IGUALACION, yycolumn, yyline, yytext());
            }
          // fall through
          case 96: break;
          case 32:
            { return new Symbol(sym.MAYOR_IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 97: break;
          case 33:
            { return new Symbol(sym.DO, yycolumn, yyline, yytext());
            }
          // fall through
          case 98: break;
          case 34:
            { return new Symbol(sym.IF, yycolumn, yyline, yytext());
            }
          // fall through
          case 99: break;
          case 35:
            { return new Symbol(sym.OR, yycolumn, yyline, yytext());
            }
          // fall through
          case 100: break;
          case 36:
            { return new Symbol(sym.CARACTER, yycolumn, yyline, yytext().replace("\'", ""));
            }
          // fall through
          case 101: break;
          case 37:
            { return new Symbol(sym.DECIMAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 102: break;
          case 38:
            { return new Symbol(sym.FOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 103: break;
          case 39:
            { return new Symbol(sym.INT, yycolumn, yyline, yytext());
            }
          // fall through
          case 104: break;
          case 40:
            { return new Symbol(sym.NEW, yycolumn, yyline, yytext());
            }
          // fall through
          case 105: break;
          case 41:
            { return new Symbol(sym.VARIABLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 106: break;
          case 42:
            { return new Symbol(sym.BOOL, yycolumn, yyline, yytext());
            }
          // fall through
          case 107: break;
          case 43:
            { return new Symbol(sym.CHAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 108: break;
          case 44:
            { return new Symbol(sym.ELSE, yycolumn, yyline, yytext());
            }
          // fall through
          case 109: break;
          case 45:
            { return new Symbol(sym.FIND, yycolumn, yyline, yytext());
            }
          // fall through
          case 110: break;
          case 46:
            { return new Symbol(sym.LIST, yycolumn, yyline, yytext());
            }
          // fall through
          case 111: break;
          case 47:
            { return new Symbol(sym.BOOLEANO, yycolumn, yyline, yytext());
            }
          // fall through
          case 112: break;
          case 48:
            { return new Symbol(sym.VOID, yycolumn, yyline, yytext());
            }
          // fall through
          case 113: break;
          case 49:
            { return new Symbol(sym.BREAK, yycolumn, yyline, yytext());
            }
          // fall through
          case 114: break;
          case 50:
            { return new Symbol(sym.CONSTANTE, yycolumn, yyline, yytext());
            }
          // fall through
          case 115: break;
          case 51:
            { return new Symbol(sym.MATCH, yycolumn, yyline, yytext());
            }
          // fall through
          case 116: break;
          case 52:
            { return new Symbol(sym.ROUND, yycolumn, yyline, yytext());
            }
          // fall through
          case 117: break;
          case 53:
            { return new Symbol(sym.WHILE, yycolumn, yyline, yytext());
            }
          // fall through
          case 118: break;
          case 54:
            { return new Symbol(sym.APPEND, yycolumn, yyline, yytext());
            }
          // fall through
          case 119: break;
          case 55:
            { return new Symbol(sym.DOUBLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 120: break;
          case 56:
            { return new Symbol(sym.LENGTH, yycolumn, yyline, yytext());
            }
          // fall through
          case 121: break;
          case 57:
            { return new Symbol(sym.REMOVE, yycolumn, yyline, yytext());
            }
          // fall through
          case 122: break;
          case 58:
            { return new Symbol(sym.RETURN, yycolumn, yyline, yytext());
            }
          // fall through
          case 123: break;
          case 59:
            { return new Symbol(sym.STRING, yycolumn, yyline, yytext());
            }
          // fall through
          case 124: break;
          case 60:
            { return new Symbol(sym.STRUCT, yycolumn, yyline, yytext());
            }
          // fall through
          case 125: break;
          case 61:
            { return new Symbol(sym.DEFAULT, yycolumn, yyline, yytext());
            }
          // fall through
          case 126: break;
          case 62:
            { return new Symbol(sym.PRINTLN, yycolumn, yyline, yytext());
            }
          // fall through
          case 127: break;
          case 63:
            { return new Symbol(sym.CONTINUE, yycolumn, yyline, yytext());
            }
          // fall through
          case 128: break;
          case 64:
            { return new Symbol(sym.TOSTRING, yycolumn, yyline, yytext());
            }
          // fall through
          case 129: break;
          case 65:
            { return new Symbol(sym.START_WITH, yycolumn, yyline, yytext());
            }
          // fall through
          case 130: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
