
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package interprete;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POR = 11;
  public static final int CHAR = 5;
  public static final int IGUALACION = 14;
  public static final int FIND = 57;
  public static final int REMOVE = 50;
  public static final int ENTERO = 59;
  public static final int XOR = 24;
  public static final int DOUBLE = 3;
  public static final int CONTINUE = 45;
  public static final int UNOT = 66;
  public static final int INT = 2;
  public static final int PRINTLN = 53;
  public static final int FOR = 42;
  public static final int C_CORCHETE = 30;
  public static final int MATCH = 39;
  public static final int C_LLAVE = 28;
  public static final int A_LLAVE = 27;
  public static final int CONSTANTE = 35;
  public static final int NOT = 19;
  public static final int AND = 23;
  public static final int APPEND = 49;
  public static final int IGUAL = 18;
  public static final int CARACTER = 63;
  public static final int OR = 22;
  public static final int BOOL = 4;
  public static final int DOS_P = 8;
  public static final int UMENOS = 65;
  public static final int IF = 37;
  public static final int MAYOR_Q = 21;
  public static final int ID = 64;
  public static final int DECIMAL = 60;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int MENOR_Q = 20;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int CADENA = 62;
  public static final int MODULO = 13;
  public static final int MENOS = 10;
  public static final int TOSTRING = 56;
  public static final int BREAK = 44;
  public static final int VOID = 52;
  public static final int DIFERENCIACION = 15;
  public static final int POTENCIA = 34;
  public static final int A_PARENTESIS = 25;
  public static final int GUION_BAJO = 33;
  public static final int ELSE = 38;
  public static final int PUNTO = 32;
  public static final int DIVIDIR = 12;
  public static final int VARIABLE = 36;
  public static final int START_WITH = 58;
  public static final int C_PARENTESIS = 26;
  public static final int WHILE = 41;
  public static final int LIST = 47;
  public static final int DEFAULT = 40;
  public static final int MAYOR_IGUAL = 17;
  public static final int A_CORCHETE = 29;
  public static final int BOOLEANO = 61;
  public static final int STRING = 6;
  public static final int MENOR_IGUAL = 16;
  public static final int STRUCT = 51;
  public static final int LENGTH = 55;
  public static final int ROUND = 54;
  public static final int DO = 43;
  public static final int PYC = 7;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "PYC",
  "DOS_P",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIR",
  "MODULO",
  "IGUALACION",
  "DIFERENCIACION",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IGUAL",
  "NOT",
  "MENOR_Q",
  "MAYOR_Q",
  "OR",
  "AND",
  "XOR",
  "A_PARENTESIS",
  "C_PARENTESIS",
  "A_LLAVE",
  "C_LLAVE",
  "A_CORCHETE",
  "C_CORCHETE",
  "COMA",
  "PUNTO",
  "GUION_BAJO",
  "POTENCIA",
  "CONSTANTE",
  "VARIABLE",
  "IF",
  "ELSE",
  "MATCH",
  "DEFAULT",
  "WHILE",
  "FOR",
  "DO",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "LIST",
  "NEW",
  "APPEND",
  "REMOVE",
  "STRUCT",
  "VOID",
  "PRINTLN",
  "ROUND",
  "LENGTH",
  "TOSTRING",
  "FIND",
  "START_WITH",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "CADENA",
  "CARACTER",
  "ID",
  "UMENOS",
  "UNOT"
  };
}

